2025-05-09 09:49:06,106 - pyexam - DEBUG - AuthManager initialized
2025-05-09 09:49:07,914 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 11:29:57,157 - pyexam - DEBUG - AuthManager initialized
2025-05-09 11:30:00,668 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 11:44:28,059 - pyexam - DEBUG - AuthManager initialized
2025-05-09 11:45:06,271 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 11:51:26,323 - pyexam - DEBUG - AuthManager initialized
2025-05-09 11:51:32,433 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 11:51:54,773 - pyexam - DEBUG - AuthManager initialized
2025-05-09 11:51:58,914 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 11:53:39,468 - pyexam - DEBUG - AuthManager initialized
2025-05-09 11:53:44,772 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:06:06,836 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:06:10,256 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:38:21,849 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:38:24,141 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:38:51,532 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:38:54,736 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:39:55,240 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:39:57,704 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:41:10,939 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:42:14,918 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:42:18,623 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:44:32,703 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:44:39,974 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:49:57,591 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:49:59,822 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:51:39,423 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:51:41,932 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:51:56,957 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 12:54:09,126 - pyexam - DEBUG - AuthManager initialized
2025-05-09 12:54:11,254 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:09:23,764 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:09:27,552 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:09:39,269 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:09:44,377 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:13:37,514 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:13:39,989 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:16:22,645 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:16:24,963 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:16:51,966 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:16:56,034 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:22:37,784 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:24:01,531 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:25:05,325 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:25:08,073 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:26:41,279 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:26:43,206 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:28:15,741 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:28:18,353 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:28:36,989 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:28:38,854 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:29:48,958 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:37:35,955 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:37:39,551 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:43:43,340 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:43:48,649 - pyexam - DEBUG - Attempting to fetch user: 1
2025-05-09 13:44:32,238 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:44:37,236 - pyexam - DEBUG - Attempting to fetch user: 3
2025-05-09 13:56:06,221 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:57:20,039 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:57:23,297 - pyexam - DEBUG - Attempting to fetch user: 2
2025-05-09 13:57:27,340 - pyexam - DEBUG - Attempting to fetch user: 2
2025-05-09 13:59:00,665 - pyexam - DEBUG - AuthManager initialized
2025-05-09 13:59:04,138 - pyexam - DEBUG - Attempting to fetch user: 2
2025-05-09 13:59:08,304 - pyexam - DEBUG - Attempting to fetch user: 2
